-- Basic Supabase Schema for Hybrid CRM MVP

-- 1. Contacts Table
CREATE TABLE IF NOT EXISTS contacts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    category TEXT CHECK (category IN ('família', 'amigos', 'clientes', 'conhecidos', 'parceiros', 'outros')) DEFAULT 'outros',
    priority TEXT CHECK (priority IN ('alta', 'media', 'baixa')) DEFAULT 'media',
    phone TEXT,
    email TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Events Table (Birthdays, Milestones, Anniversaries)
CREATE TABLE IF NOT EXISTS events (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    contact_id UUID REFERENCES contacts(id) ON DELETE CASCADE,
    event_type TEXT CHECK (event_type IN ('aniversario', 'conquista', 'data_importante', 'lembrete')),
    event_date DATE NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Interactions History Table
CREATE TABLE IF NOT EXISTS interactions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    contact_id UUID REFERENCES contacts(id) ON DELETE CASCADE,
    interaction_type TEXT CHECK (interaction_type IN ('mensagem_enviada', 'ligacao', 'reuniao', 'evento')),
    notes TEXT,
    interaction_date TIMESTAMPTZ DEFAULT NOW(),
    created_by TEXT DEFAULT 'system'
);

-- 4. Tasks Table (Generated by n8n or Manual)
CREATE TABLE IF NOT EXISTS tasks (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    contact_id UUID REFERENCES contacts(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    suggested_message TEXT,
    status TEXT CHECK (status IN ('pendente', 'aprovada', 'cancelada', 'concluida')) DEFAULT 'pendente',
    due_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    resolved_at TIMESTAMPTZ
);
